
version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: monitor
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  redis:
    image: redis:7

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.example
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery-worker:
    build: ./backend
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.example
    depends_on:
      - backend
      - redis

  celery-beat:
    build: ./backend
    command: celery -A backend beat -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.example
    depends_on:
      - backend
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env.example
    ports:
      - "3000:3000"
    depends_on:
      - backend
